//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleGame.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImageRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImageRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleGame.Resource.ImageRes", typeof(ImageRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AAAA                                                                        AAAA
        ///AA                                                                            AA
        ///A                                                                              A
        ///A                                                                              A
        ///                                                                                
        ///                                                                                
        ///                     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///  @  
        /// @@@ 
        ///  @  
        /// 的本地化字符串。
        /// </summary>
        internal static string Boom_1 {
            get {
                return ResourceManager.GetString("Boom_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   @
        /// @@@
        ///@@@@@
        /// @@@
        ///  @ 的本地化字符串。
        /// </summary>
        internal static string Boom_2 {
            get {
                return ResourceManager.GetString("Boom_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  @@@
        ///@@ @@
        ///@   @
        ///@@ @@
        /// @@@ 的本地化字符串。
        /// </summary>
        internal static string Boom_3 {
            get {
                return ResourceManager.GetString("Boom_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  @ @
        ///@   @
        ///     
        ///@   @
        /// @ @ 的本地化字符串。
        /// </summary>
        internal static string Boom_4 {
            get {
                return ResourceManager.GetString("Boom_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  ---
        ///|+++|
        ///|+++|
        ///|+++|
        /// --- 的本地化字符串。
        /// </summary>
        internal static string BoomWarning {
            get {
                return ResourceManager.GetString("BoomWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   OOO 
        /// OBOSO
        /// OBOSO
        ///  OOO  的本地化字符串。
        /// </summary>
        internal static string Boss_1 {
            get {
                return ResourceManager.GetString("Boss_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   OOO 
        /// OEEEO
        /// OEEEO
        ///  OOO  的本地化字符串。
        /// </summary>
        internal static string Boss_2 {
            get {
                return ResourceManager.GetString("Boss_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |
        ///v 的本地化字符串。
        /// </summary>
        internal static string Bullet_ArrowDown {
            get {
                return ResourceManager.GetString("Bullet_ArrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;- 的本地化字符串。
        /// </summary>
        internal static string Bullet_ArrowLeft {
            get {
                return ResourceManager.GetString("Bullet_ArrowLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -&gt; 的本地化字符串。
        /// </summary>
        internal static string Bullet_ArrowRight {
            get {
                return ResourceManager.GetString("Bullet_ArrowRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^
        ///| 的本地化字符串。
        /// </summary>
        internal static string Bullet_ArrowUp {
            get {
                return ResourceManager.GetString("Bullet_ArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 e 的本地化字符串。
        /// </summary>
        internal static string Enemy_1 {
            get {
                return ResourceManager.GetString("Enemy_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E 的本地化字符串。
        /// </summary>
        internal static string Enemy_2 {
            get {
                return ResourceManager.GetString("Enemy_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * 的本地化字符串。
        /// </summary>
        internal static string EnemyBullet {
            get {
                return ResourceManager.GetString("EnemyBullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似                                                                                 
        ///                                                                                
        ///                                                                                
        ///                                                                                
        ///                                                                                
        ///                                                                                
        ///                     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Foreground {
            get {
                return ResourceManager.GetString("Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P 的本地化字符串。
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 p 的本地化字符串。
        /// </summary>
        internal static string Player_1 {
            get {
                return ResourceManager.GetString("Player_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P 的本地化字符串。
        /// </summary>
        internal static string Player_2 {
            get {
                return ResourceManager.GetString("Player_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 . 的本地化字符串。
        /// </summary>
        internal static string PlayerBullet {
            get {
                return ResourceManager.GetString("PlayerBullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 O 的本地化字符串。
        /// </summary>
        internal static string TargetRing_1 {
            get {
                return ResourceManager.GetString("TargetRing_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 o 的本地化字符串。
        /// </summary>
        internal static string TargetRing_2 {
            get {
                return ResourceManager.GetString("TargetRing_2", resourceCulture);
            }
        }
    }
}
